import Config

# Configure your database
config :example_phoenix, ExamplePhoenix.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "example_phoenix_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :example_phoenix, ExamplePhoenixWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "iPDrZuPVtDIs1XMTTJBJyvaJKF6ZJTyp7KSQe6LYM2M4bFCPxi/REuixeejcNGJw",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:example_phoenix, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:example_phoenix, ~w(--watch)]}
  ],
  static_paths: ["priv/static/uploads"]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :example_phoenix, ExamplePhoenixWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/example_phoenix_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :example_phoenix, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :ex_aws,
  access_key_id: "522e5650436a033ffd13c065884753ff",
  secret_access_key: "463bf46ba28ffb04f307d54c47d8a0cd00e33eee1c2dbfb7b36a4ee3f2756fb9"

config :ex_aws, :s3,
  scheme: "https://",
  host: "436b6a515d460c25108e569e4cc2ffdf.r2.cloudflarestorage.com",
  region: "auto"

config :example_phoenix, :r2,
  bucket_name: "lyra",
  public_url: "https://pub-11496457277242a8b2070cbd977c20ef.r2.dev"
